// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByaSP4gOg0rnspYOBRFA-hSfMAb8Uy0j0',
    appId: '1:704553122764:web:fa6a263364cfb3f7737b69',
    messagingSenderId: '704553122764',
    projectId: 'project-peace-8d684',
    authDomain: 'project-peace-8d684.firebaseapp.com',
    storageBucket: 'project-peace-8d684.appspot.com',
    measurementId: 'G-55ZWCLGBNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfzYpwGLz6yJxFVaHesDk6lAfAsAc1Euk',
    appId: '1:704553122764:android:1fd554098dec5a23737b69',
    messagingSenderId: '704553122764',
    projectId: 'project-peace-8d684',
    storageBucket: 'project-peace-8d684.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4BUHd6BYw2X5x16Yt41m8vUlrzKEBTIw',
    appId: '1:704553122764:ios:e60d75402a101926737b69',
    messagingSenderId: '704553122764',
    projectId: 'project-peace-8d684',
    storageBucket: 'project-peace-8d684.appspot.com',
    iosClientId: '704553122764-meuecl8me09cq3vp1t04nhat21u17igv.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectPeaceApp',
  );
}
